### ISSUE TITLE
pip on requirements file gives error

### ISSUE THREAD

**Issue by pmnerfed** [dennybritz/nn-from-scratch#1]
The following error comes when I try using pip on the given requirements file

Could not find a version that satisfies the requirement functools32==3.2.3.post2 (from -r requirements.txt (line 6)) (from versions: 3.2.3-1, 3.2.3-1, 3.2.3-2, 3.2.3-2)

**Comment by dennybritz** [comment]
Can you try upgrading your pip version? 

```
sudo pip install -U pip
```

**Comment by pmnerfed** [comment]
Thanks that worked and I also had to use pip2
