### ISSUE TITLE
Could I translate your article into Chinese and put it online?

### ISSUE THREAD

**Issue by YoungYo** [dennybritz/nn-from-scratch#19]
Hello， Denny Britz！I come from China, a beginner of Deep Learning. Recently, I read your article [Implementing a Neural Network from Scratch in Python – An Introduction](http://www.wildml.com/2015/09/implementing-a-neural-network-from-scratch/). I think it is very great and helpful for these beginner like me. So I want to translate it into Chinese and put it online to let more people learn it, and I sincerely want to ask for your agreement. 
 Look forward to your reply. 
(My English is not very good, I hope you can forgive me if somewhere I use wrong vocabulary and grammar.)

**Comment by dennybritz** [comment]
Sure, no problem!

**Comment by YoungYo** [comment]
Thank you very much!!! And...In the mainland of China, the website of twitter and facebook is blocked. Therefore ,for I can contact you when I want to translate your other posts or blogs or articles, would you please provide me with another contact information, such as email address?
