### ISSUE TITLE
WildML is down

### ISSUE THREAD

**Issue by martinhorvath** [dennybritz/nn-from-scratch#27]
Hey Denny,

I really appreciate the efforts to build this masterpiece of "AI under the hood". Unfortunately I lost my pdf copy of your blogpost and realised that the page seems to be down. Would you mind uploading a pdf version to the repo?

Best regards,
Martin

**Comment by mbrukman** [comment]
FWIW, I'm not the author of the blog post or this repo, but if you're referring to the URL in the README: http://www.wildml.com/2015/09/implementing-a-neural-network-from-scratch/ it seems to currently serve a redirect to https://dennybritz.com/posts/wildml/implementing-a-neural-network-from-scratch/ so it should be accessible for you now.

Hope this helps!

**Comment by martinhorvath** [comment]
Thanks a lot!
