### ISSUE TITLE
[SOLVED] matplotlib import error

### ISSUE THREAD

**Issue by faizankshaikh** [dennybritz/nn-from-scratch#6]
when we import matplotlib, it gives the error `numpy.core.multiarray failed to import`.

To solved this I referred [this thread](http://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import) and upgraded numpy version to 11.1.

Just thought you should know, if in future somebody has the same problem.

**Comment by dennybritz** [comment]
Thanks!

**Comment by faizankshaikh** [comment]
Btw maybe you should change the requirements.txt file. Try to run the code locally, and check if the problem occurs on your end too.
